SPECIALTY_GENERAL:str = "GENERAL"
SPECIALTY_BACKEND_JAVA:str = "BACKEND JAVA"
SPECIALTY_FRONTEND_WEB:str = "FRONTEND WEB"
SPECIALTY_FRONTEND_IOS:str = "FRONTEND IOS"
SPECIALTY_FRONTEND_ANDROID:str = "FRONTEND ANDROID"
SPECIALTY_FRONTEND_MOBILE:str = "FRONTEND MOBILE"

STATE_FINALIZADO:str = "FINALIZADO"

SPECIALTYS_SCOPE = [SPECIALTY_BACKEND_JAVA,SPECIALTY_FRONTEND_WEB,SPECIALTY_FRONTEND_IOS,SPECIALTY_FRONTEND_ANDROID]
