SPECIALTY_GENERAL:str = "GENERAL"
SPECIALTY_BACKEND_JAVA:str = "BACKEND JAVA"
SPECIALTY_FRONTEND_WEB:str = "FRONTEND WEB"
SPECIALTY_FRONTEND_IOS:str = "FRONTEND IOS"
SPECIALTY_FRONTEND_ANDROID:str = "FRONTEND ANDROID"
SPECIALTY_FRONTEND_MOBILE:str = "FRONTEND MOBILE"

SPECIALTYS_SCOPE_SEE = [SPECIALTY_BACKEND_JAVA,SPECIALTY_FRONTEND_WEB,SPECIALTY_FRONTEND_IOS,SPECIALTY_FRONTEND_ANDROID]
SPECIALTYS_SCOPE = [SPECIALTY_BACKEND_JAVA,SPECIALTY_FRONTEND_WEB,SPECIALTY_FRONTEND_IOS,SPECIALTY_FRONTEND_ANDROID,SPECIALTY_FRONTEND_MOBILE]

ARRAY_QUIZ_METRICS = ["patrones","principios","asserts","restricciones","mocks","stubs","naming_convention","coverage_valor"]

TYPE_INFORMATION_SONAR_AUTO:str = "AUTO"
TYPE_INFORMATION_SONAR_MANUAL:str = "MANUAL"

RANGE_PENALTY_PERCENTAGE_RATIO_EXECUTION_SONAR:float = 50.0
PENALTY_PERCENTAGE_RATIO_EXECUTION_SONAR:float = -0.5

YES = "Y"